import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AppSidebar } from "@/components/AppSidebar";
import { TRPCReactProvider } from "@/trpc/client/trpc-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { headers } from "next/headers";
import { dark, shadesOfPurple } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";
import ErrorBoundary from "@/components/Error/ErrorBoundary";
import { ErrorProvider } from "@/components/Error/ErrorProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const heads = new Headers(await headers());
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [dark],
        variables: { colorPrimary: "blue" },
        signIn: {
          baseTheme: [shadesOfPurple],
          variables: { colorPrimary: "green" },
        },
      }}
    >
      <TRPCReactProvider headers={heads}>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ErrorProvider>
                <ErrorBoundary>
                  <SidebarProvider>
                    <AppSidebar />
                    <SidebarTrigger />
                    {children}
                    <Toaster />
                  </SidebarProvider>
                </ErrorBoundary>
              </ErrorProvider>
            </ThemeProvider>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
